if [ -f /etc/bash.bashrc ]; then
    . /etc/bash.bashrc
fi

# Custom aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'

# Custom prompt (optional)
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Initialize direnv
eval "$(direnv hook bash)"
